tunnel: 554aed7c-f95e-4e18-a771-472ddeb4d2ec
credentials-file: /home/abed/.cloudflared/554aed7c-f95e-4e18-a771-472ddeb4d2ec.json

ingress:
  - hostname: ailearning.cbtbags.com
    path: /api-proxy/*
    service: http://10.0.0.10:8001
    originRequest:
      noTLSVerify: true
  - hostname: ailearning.cbtbags.com
    service: http://localhost:5174
    originRequest:
      noTLSVerify: true
  - hostname: apiailearning.cbtbags.com
    service: http://10.0.0.10:8001
    originRequest:
      noTLSVerify: true
  - service: http_status:404